/* Host test for the partition scanner.
 *
 * This exists because of a bug that shipped: part_scan treated a 0xAA55
 * signature as proof of a partition table, and a FAT boot sector has one too -
 * so the data disk, a filesystem starting at sector 0 with no table at all,
 * was parsed as partitioned, produced zero volumes, and the kernel booted with
 * nothing mounted. The failure was silent at every layer: the scan succeeded,
 * it just found nothing.
 *
 * Nothing in ring 3 could have caught that. verification.c can check that a
 * volume EXISTS on the machine it is running on, which is one disk in one
 * layout; it cannot present the scanner with a GPT disk, a hybrid MBR, or a
 * primary header that has been zeroed. Those are BUILD checks by the standing
 * rule, and this is where they go.
 *
 * The images are generated by tests/host/mkimg.py rather than committed as
 * binaries, so the expected values below can be read against the code that
 * produced them instead of against a hexdump.
 *
 * Build and run:  python3 tests/host/mkimg.py && cc -o part_test ... && ./part_test
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "dev_stub.h"
#include "device.h"
#include "part.h"

/* The device stub is shared with fat_test.c - see dev_stub.c. That sharing is
 * itself the point being demonstrated: part.c reads through dev_read, so a
 * file on the host substitutes for a disk with no change to the code under
 * test. A scanner wired directly to ATA could only be tested on real hardware,
 * which is to say not at all.
 */

static device_t   dev;
static dev_stub_t dev_backing;

/* Images live wherever run.sh built them, so the directory is passed in rather
 * than hardcoded - a test that only runs when the fixtures happen to be in
 * /tmp is a test that quietly stops running. */
static const char *path(const char *dir, const char *name) {
    static char buf[512];
    snprintf(buf, sizeof(buf), "%s/%s", dir, name);
    return buf;
}

static int failures;
static int passes;

static void ok(int cond, const char *what) {
    printf("  %s  %s\n", cond ? "ok  " : "FAIL", what);
    if (cond) passes++; else failures++;
}

static int scan(const char *path, part_entry_t *out, part_table_t *table) {
    if (dev_stub_load(&dev, &dev_backing, path) != 0) {
        printf("  FAIL  cannot open %s (run tests/host/mkimg.py first)\n", path);
        failures++;
        *table = PART_TABLE_NONE;
        return -1;
    }
    return part_scan(&dev, out, PART_MAX, table);
}

int part_run_tests(const char *dir) {
    part_entry_t p[PART_MAX];
    part_table_t t;
    int n;

    printf("part_scan\n");

    /* --- the regression -------------------------------------------------
     *
     * A FAT filesystem at sector 0, with the 0xAA55 signature every FAT boot
     * sector carries. This is the data disk, and it is the case that failed:
     * it MUST come back as PART_TABLE_NONE with zero partitions, which
     * volume.c reads as "the whole disk is one volume".
     *
     * The control is the table kind, not just the count. Returning zero
     * partitions with PART_TABLE_MBR is what the broken version did - the
     * count alone cannot tell the two apart, and only one of them mounts. */
    n = scan(path(dir, "fat_superfloppy.img"), p, &t);
    ok(n == 0, "a FAT superfloppy reports no partitions");
    ok(t == PART_TABLE_NONE,
       "and reports NO TABLE, not an empty MBR (the shipped bug)");

    /* A disk with no signature at all, for contrast: the case the original
     * rule did handle. Both must reach PART_TABLE_NONE by different routes. */
    n = scan(path(dir, "raw.img"), p, &t);
    ok(n == 0 && t == PART_TABLE_NONE, "an unformatted disk reports no table");

    /* --- MBR ------------------------------------------------------------- */
    n = scan(path(dir, "mbr.img"), p, &t);
    ok(t == PART_TABLE_MBR, "a real MBR is recognised as MBR");
    ok(n == 2, "and both partitions are found");
    if (n == 2) {
        ok(p[0].start_lba == 64 && p[0].sectors == 512 &&
           p[0].mbr_type == 0x83 && p[0].bootable == 1,
           "first entry: LBA, size, type and boot flag all match");
        ok(p[1].start_lba == 1024 && p[1].mbr_type == 0x0b,
           "second entry too");
    }

    /* --- GPT --------------------------------------------------------------
     *
     * The path that had never executed. Everything on the machine takes the
     * PART_TABLE_NONE branch, so until this test ran, scan_gpt, the header
     * CRC, the entry-array CRC folded across sector reads, and the inclusive
     * last-LBA arithmetic were all code that had been read but never run. */
    n = scan(path(dir, "gpt.img"), p, &t);
    ok(t == PART_TABLE_GPT, "a protective MBR leads to the GPT");
    ok(n == 2, "and both GPT entries are found");
    if (n == 2) {
        /* Entries are first/last INCLUSIVE on disk. 2048..2559 is 512
         * sectors, not 511 - the off-by-one that would produce a volume one
         * sector short, which a filesystem only notices when something lands
         * in its final cluster. */
        ok(p[0].start_lba == 2048 && p[0].sectors == 512,
           "inclusive last-LBA arithmetic gives the right size");
        ok(p[1].start_lba == 2560 && p[1].sectors == 1441,
           "and for the second entry");
        /* The EFI system partition is not a data partition; the Linux one is.
         * A whitelist would have refused both - see part_type_is_data. */
        ok(!part_type_is_data(&p[0]), "the EFI system partition is not data");
        ok(part_type_is_data(&p[1]), "but the filesystem partition is");
    }

    /* The backup header, which is the entire reason GPT writes one: a primary
     * destroyed by a tool that wrote over LBA 1. */
    n = scan(path(dir, "gpt_backup.img"), p, &t);
    ok(t == PART_TABLE_GPT && n == 2,
       "a zeroed primary header falls back to the backup");

    /* A hybrid MBR - a protective 0xEE entry BESIDE a real one, which is what
     * a dual-boot installer writes. The protective test must not fire here,
     * or three real partitions get discarded. */
    n = scan(path(dir, "gpt_hybrid.img"), p, &t);
    ok(n >= 1, "a hybrid MBR is not mistaken for a purely protective one");

    /* --- CRC ------------------------------------------------------------
     *
     * The check that cannot be made from inside the kernel. A CRC wrong in a
     * consistent way validates every table it computes itself and rejects
     * every real one; the only way to know is against a value computed
     * elsewhere. 0xCBF43926 for "123456789" is the standard vector every
     * conforming CRC-32 agrees on. */
    printf("part_crc32\n");
    ok(part_crc32("123456789", 9) == 0xCBF43926u,
       "matches the standard CRC-32 check value");
    ok(part_crc32("", 0) == 0u, "and the empty input is zero");

    (void)passes;
    (void)dir;
    return failures;
}
