#ifndef LKPI_DEMO_H
#define LKPI_DEMO_H

/* Generated by module_pci_driver(lkpi_demo_driver) in lkpi_demo.c (see
 * linux/pci.h) - not hand-written, but declared here since nothing about a
 * macro-generated name is guessable from flk.c. Registers lkpi_demo_driver
 * on the "pci" devclass; call once, before bus_attach_children(pci_root()). */
int lkpi_demo_driver_lkpi_module_init(void);

#endif
