#ifndef NEWBUS_COMPAT_DEMO_H
#define NEWBUS_COMPAT_DEMO_H

/* Generated by DRIVER_MODULE(newbus_compat_demo, pci, newbus_demo_driver,
 * 0, 0) in newbus_compat_demo.c (see kernel/include/sys/bus.h). Registers
 * newbus_demo_driver on the "pci" devclass; call once, before
 * bus_attach_children(pci_root()). */
int newbus_compat_demo_pci_newbus_module_init(void);

#endif
