#ifndef PSM_H
#define PSM_H

#include "typesk.h"

/* The PS/2 mouse driver's non-Newbus surface. The driver itself
 * (kernel/dev/psm.c) is a FreeBSD-idiom Newbus driver on the atkbdc bus and
 * registers through psm_atkbdc_newbus_module_init(), which DRIVER_MODULE
 * generates; these two are for flk.c. Plain types only: this header is
 * included next to kernel/include/bus.h, which kernel/include/sys/bus.h (what
 * psm.c is written against) must never meet. */

/* Generated by DRIVER_MODULE(psm, atkbdc, ...) in psm.c. Call before
 * atkbdc_init. */
int psm_atkbdc_newbus_module_init(void);

/* Boot selftest, after sti: injects packets through the controller's
 * loopback command so they arrive exactly as a mouse's would - IRQ 12, the
 * handler, the packet decoder, mouse_report - and checks the events that come
 * out of the queue. Prints "psm: selftest passed" / "psm: selftest FAILED
 * (n)", or why it did not run. Returns the failures. */
int psm_selftest(void);

/* Packets decoded, resynchronisations, overflowed packets, dropped reports. */
void psm_report(uint8 color);

#endif
