/* opt_inet.h - GENERATED by config(8) upstream, written by hand here.
 *
 * THIS ONE IS NOT EMPTY, and the difference matters more than any other
 * opt_ file. FreeBSD's network source is full of "#ifdef INET" - the ARP
 * hooks in ether_input, the IPv4 branch of ether_output's address
 * resolution, the whole of netinet. Leaving it undefined does not fail to
 * build; it builds an Ethernet layer with no IPv4 in it, which is a
 * perfectly quiet way to end up with a NIC that can send raw frames and
 * nothing else.
 */
#define INET 1
