#!/usr/bin/env python3
"""Generate ntdll's syscall-number header from the kernel's.

The DLL and the kernel must agree on every number, and this tree has already
produced three rival copies of one constant - NT_TEB_BASE lived in two headers
at two different addresses, and in a Python script as a third. A hand-kept
list here would be a fourth, in a fourth language, guarded by a comment.

So the numbers have exactly one home, kernel/include/nt.h, and this reads them
out of it. A number changed in the kernel and not in the DLL is then not
possible rather than merely discouraged.

The parse is deliberately dumb: one regular expression over #define
NT_SYS_<name> <number>. If it stops matching, the build fails loudly here
rather than producing a DLL that calls the wrong kernel.
"""

import os
import re
import sys

PATTERN = re.compile(r"^#define\s+NT_SYS_([A-Z0-9_]+)\s+(0x[0-9A-Fa-f]+|\d+)",
                     re.MULTILINE)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    header = os.path.join(here, "..", "..", "kernel", "include", "nt.h")
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, "ntsyscalls.h")

    with open(header) as f:
        found = PATTERN.findall(f.read())

    if not found:
        sys.exit(f"mknums.py: no NT_SYS_* defines found in {header}")

    lines = [
        "/* GENERATED by src/ntdll/mknums.py - do not edit.",
        " *",
        " * Source of truth: kernel/include/nt.h. Edit the numbers there.",
        " */",
        "#ifndef NTSYSCALLS_H",
        "#define NTSYSCALLS_H",
        "",
    ]
    width = max(len(name) for name, _ in found) + len("NT_SYS_")
    for name, value in found:
        lines.append(f"#define {('NT_SYS_' + name).ljust(width)}  {value}")
    lines += ["", "#endif", ""]

    with open(out, "w") as f:
        f.write("\n".join(lines))
    print(f"{out}: {len(found)} syscall numbers from kernel/include/nt.h")


if __name__ == "__main__":
    main()
